
spring:
  profiles:
    active: security
  config:
    import: optional:application-local.yml
  application:
    name: backend
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "client-id"
            client-secret: "client-secret"
          google:
            client-id: "client-id"
            client-secret: "client-secret"
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb

progi:
  frontend:
    url: "http://localhost:5173"